### PR TITLE
Introduce TypeToken and use generics for interfaces

### LINKED ISSUE #48: Wrong return type when null is used for default value
We have just encountered a bug around type generics.

```diff
     public Observable<Boolean> observePreference() {
-        return mPrefser.getAndObserve(KEY, String.class, null); // emits String, but inferred as Observable<Boolean> by return type
+        return mPrefser.<String>getAndObserve(KEY, String.class, null)
+                .map(this::mapToBoolean);
     }
 ```

Second parameter of getAndObserve is raw type without type parameter: `Class`.
`Class<T>` should be used instead to make type inference work well.

But this causes unchecked assignment warnings when used with List.class, as type of List content is not specified.
Maybe related to issue about List type: #44.

### PR DESCRIPTION
**Pull request by ypresto**
Fixes #48

This PR contains interface change on raw type (i.e. `List`).
Type token issue (#44) should be fixed first.

### CODE REVIEW

**Comment by pwittchen** [comment]
Thank you for your Pull Request!
I checked out to your branch, but unfortunately unit tests in `PrefserTest` cannot be compiled. Can you fix unit tests or update your change?

**Comment by ypresto** [comment]
Despite of that this is ideal use of generics, it is incompatible with `List.class` argument.

```java
RecordingObserver<List<Double>> observer = new RecordingObserver<>();
prefser.observe(givenKey, List.class, defaultDoubles) // Observable<List>
    .subscribe(observer); // Incompatible, Observable<List> vs Observer<List<Double>
```

So interface change for treating List with type parameter should be done before this compile error is fixed.

**Comment by pwittchen** [comment]
If you know, what changes have to be performed in order to fix tests, feel free to make it on your branch within this PR. You can also update tests or interface. I'd like to merge your branch, but I want to be sure that everything will work fine after the merge.

**Comment by ypresto** [comment]
> You can also update tests or interface.

Thanks, I'll add new method for treating list, and it'll be incompatible
change with older version :)

2015年7月27日(月) 18:10 Piotr Wittchen <notifications@github.com>:

> If you know, what changes have to be performed in order to fix tests, feel
> free to make it on your branch within this PR. You can also update tests or
> interface. I'd like to merge your branch, but I want to be sure that
> everything will work fine after the merge.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pwittchen/prefser/pull/49#issuecomment-125137021>.
>
-- 
--
 */*/ Yuya Tanaka
*/*/* 090-5679-5099
/*/*  yuya.presto@gmail.com

**Comment by ypresto** [comment]
Done! This is destructive interface change.

**Comment by pwittchen** [comment]
Great! Thanks for your effort.
I will review and check it ASAP. When everything is fine I'll be eager to merge it.

**Pull request merged**
